#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
(
  flock -n 9 || exit 0
  git ls-files --full-name | grep -E '\.(c|cpp|h)$' | \
    cscope -b -i- -F "$dir/cscope.out" -f "$dir/cscope.out"
) 9>"$dir/cscope.out.lock"
